In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/SafeBite_preprocessed_data.csv')

In [ ]:
df.head(10)

Food Product  Main Ingredient  Sweetener    Fat/Oil  Seasoning  Allergens  \
0      6.170000         6.170000  12.343736  12.471786  13.408000   6.170000   
1     10.150000        10.150000  12.387473  12.519167  13.806000  10.150000   
2     12.500000        17.480000  12.371511  12.031228  11.584000  17.480000   
3     13.223333        19.650000  12.379317  12.069298  11.801000  19.650000   
4     12.397588        17.925000  12.403237  12.185965  12.466000  12.072073   
5     12.397588        12.397588  12.346264  11.857381  13.725000  12.083171   
6     12.397588        12.397588  12.387802  12.519524  12.935000  12.129268   
7     17.330000        14.970000  12.388273  13.072697  13.690000  12.021341   
8     12.397588        10.980000  12.397410  14.203333  10.980000  12.052317   
9     10.675000        10.056667  13.222727  12.052500  12.732105  12.041098   

   Price ($)  Customer rating (Out of 5)  Prediction  
0      10.15                         3.1           0  
1       6.17                         4.5           0  
2      19.65                         4.1           0  
3      17.48                         4.7           0  
4      10.83                         3.7           0  
5       9.92                         2.3           0  
6       6.14                         3.2           0  
7      14.99                         4.8           0  
8      12.45                         3.8           0  
9      13.37                         3.2           0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Food Product                398 non-null    float64
 1   Main Ingredient             398 non-null    float64
 2   Sweetener                   398 non-null    float64
 3   Fat/Oil                     398 non-null    float64
 4   Seasoning                   398 non-null    float64
 5   Allergens                   398 non-null    float64
 6   Price ($)                   398 non-null    float64
 7   Customer rating (Out of 5)  398 non-null    float64
 8   Prediction                  398 non-null    int64  
dtypes: float64(8), int64(1)
memory usage: 28.1 KB


In [ ]:
df.shape

(398, 9)

#**Splitting the Dataset:**

In [ ]:
from sklearn.model_selection import train_test_split

# Splitting the dataset into X (features) and y (target variable):

X = df.drop(columns=['Prediction'])
y = df['Prediction']

print("Shape of X (features):", X.shape)
print("Shape of y (target):", y.shape)

# 80-20 Split:

X_train_80, X_test_80, y_train_80, y_test_80 = train_test_split(X, y, test_size=0.2, random_state=42)

print("\n80:20 Split:")
print("X_train_80 shape:", X_train_80.shape)
print("X_test_80 shape:", X_test_80.shape)
print("y_train_80 shape:", y_train_80.shape)
print("y_test_80 shape:", y_test_80.shape)

Shape of X (features): (398, 8)
Shape of y (target): (398,)

80:20 Split:
X_train_80 shape: (318, 8)
X_test_80 shape: (80, 8)
y_train_80 shape: (318,)
y_test_80 shape: (80,)


In [ ]:
# 70-30 Split:

X_train_70, X_test_70, y_train_70, y_test_70 = train_test_split(X, y, test_size=0.3, random_state=42)

print("\n70:30 Split:")
print("X_train_70 shape:", X_train_70.shape)
print("X_test_70 shape:", X_test_70.shape)
print("y_train_70 shape:", y_train_70.shape)
print("y_test_70 shape:", y_test_70.shape)


70:30 Split:
X_train_70 shape: (278, 8)
X_test_70 shape: (120, 8)
y_train_70 shape: (278,)
y_test_70 shape: (120,)


In [ ]:
print(X_train_70.head())

     Food Product  Main Ingredient  Sweetener    Fat/Oil  Seasoning  \
157     12.397588        11.913500  12.419388  13.169888  12.397588   
109      9.550000        12.446000  12.400108  13.109663  10.360000   
17      14.990000        14.385000  12.379856  13.046404  12.595000   
253     18.760000        15.433636  12.415324  12.244912  18.760000   
24      15.675000        11.834667  12.402374  12.397588  12.397588   

     Allergens  Price ($)  Customer rating (Out of 5)  
157  12.205238       6.34                         3.1  
109   9.028333      11.70                         4.5  
17   11.992805      17.33                         3.1  
253  12.197551       7.47                         2.4  
24   12.069146      11.07                         4.4  


In [ ]:
print(X_test_70.head())

     Food Product  Main Ingredient  Sweetener    Fat/Oil  Seasoning  \
198     12.397588        11.914833  12.419676  13.170787  12.397588   
396     16.560000        14.556667  12.281319  12.404167  12.670000   
33      13.930000        14.760000  12.411007  12.489405  12.397588   
208     17.430000        13.085000  12.421871  13.177640  12.440000   
93      12.397588        12.397588  12.392590  12.134035  12.397588   

     Allergens  Price ($)  Customer rating (Out of 5)  
198  12.205782       6.26                         3.0  
396  12.310000      15.83                         2.4  
33   12.098415       8.67                         4.9  
208  12.209932       5.65                         3.9  
93   13.470000      13.79                         2.2  


# **LOGISTIC REGRESSION MODEL :**

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize the Logistic Regression model
logreg = LogisticRegression(max_iter=1000, random_state=42)

# Train the model on the 80:20 split
logreg.fit(X_train_80, y_train_80)

y_pred_80 = logreg.predict(X_test_80)

accuracy_80 = accuracy_score(y_test_80, y_pred_80)
print("Accuracy on 80:20 split (in %):", accuracy_80*100)

print("\nClassification Report on 80:20 split:\n", classification_report(y_test_80, y_pred_80))

print("Confusion Matrix on 80:20 split:\n", confusion_matrix(y_test_80, y_pred_80))

Accuracy on 80:20 split (in %): 63.74999999999999

Classification Report on 80:20 split:
               precision    recall  f1-score   support

           0       0.70      0.86      0.78        58
           1       0.11      0.05      0.06        22

    accuracy                           0.64        80
   macro avg       0.41      0.45      0.42        80
weighted avg       0.54      0.64      0.58        80

Confusion Matrix on 80:20 split:
 [[50  8]
 [21  1]]


In [ ]:
# LOGISTIC REGRESSION (Without Scaling):

logreg = LogisticRegression(max_iter=1000, random_state=42)

# Train the model on the 70:30 split:
logreg.fit(X_train_70, y_train_70)

y_pred_70 = logreg.predict(X_test_70)

accuracy_70 = accuracy_score(y_test_70, y_pred_70)

print("Accuracy on 70:30 split (in %):", accuracy_70*100)

print("\nClassification Report on 70:30 split:\n", classification_report(y_test_70, y_pred_70))

print("Confusion Matrix on 70:30 split:\n", confusion_matrix(y_test_70, y_pred_70))

Accuracy on 70:30 split (in %): 61.66666666666667

Classification Report on 70:30 split:
               precision    recall  f1-score   support

           0       0.70      0.84      0.76        87
           1       0.07      0.03      0.04        33

    accuracy                           0.62       120
   macro avg       0.38      0.43      0.40       120
weighted avg       0.52      0.62      0.56       120

Confusion Matrix on 70:30 split:
 [[73 14]
 [32  1]]


In [ ]:
logreg_train_accuracy = logreg.score(X_train_70, y_train_70)
logreg_test_accuracy = logreg.score(X_test_70, y_test_70)

print("Logistic Regression Training Accuracy (in %):", logreg_train_accuracy*100)
print("\nLogistic Regression Testing Accuracy (in %):", logreg_test_accuracy*100)

Logistic Regression Training Accuracy (in %): 58.63309352517986

Logistic Regression Testing Accuracy (in %): 61.66666666666667


In [ ]:
# LOGISTIC REGRESSION (After Scaling):

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Scaling for 70:30 split:
X_train_70_scaled = scaler.fit_transform(X_train_70)
X_test_70_scaled = scaler.transform(X_test_70)

# Training and evaluating on 70:30 split:
logreg.fit(X_train_70_scaled, y_train_70)
y_pred_70_scaled = logreg.predict(X_test_70_scaled)

accuracy_70_scaled = accuracy_score(y_test_70, y_pred_70_scaled)

print("Results on 70:30 split after scaling:")
print("\nAccuracy (in %):", accuracy_70_scaled*100)

print("\nClassification Report:\n", classification_report(y_test_70, y_pred_70_scaled))

print("Confusion Matrix:\n", confusion_matrix(y_test_70, y_pred_70_scaled))

Results on 70:30 split after scaling:

Accuracy (in %): 61.66666666666667

Classification Report:
               precision    recall  f1-score   support

           0       0.70      0.84      0.76        87
           1       0.07      0.03      0.04        33

    accuracy                           0.62       120
   macro avg       0.38      0.43      0.40       120
weighted avg       0.52      0.62      0.56       120

Confusion Matrix:
 [[73 14]
 [32  1]]


In [ ]:
logreg_train_accuracy = logreg.score(X_train_70_scaled, y_train_70)
logreg_test_accuracy = logreg.score(X_test_70_scaled, y_test_70)

print("Logistic Regression Training Accuracy (in %):", logreg_train_accuracy*100)
print("\nLogistic Regression Testing Accuracy (in %):", logreg_test_accuracy*100)

Logistic Regression Training Accuracy (in %): 58.63309352517986

Logistic Regression Testing Accuracy (in %): 61.66666666666667


# **RANDOM FOREST CLASSIFIER MODEL :**

In [ ]:
# RANDOM FOREST CLASSIFIER:

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()


# Training the model on the 70:30 split:
rf.fit(X_train_70, y_train_70)

# Predictions on the test set:
y_pred_70_rf = rf.predict(X_test_70)

accuracy_70_rf = accuracy_score(y_test_70, y_pred_70_rf)

print("Random Forest Accuracy on 70:30 split (in %):", accuracy_70_rf*100)

print("\nClassification Report:\n", classification_report(y_test_70, y_pred_70_rf))

print("Confusion Matrix:\n", confusion_matrix(y_test_70, y_pred_70_rf))

Random Forest Accuracy on 70:30 split (in %): 98.33333333333333

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99        87
           1       0.97      0.97      0.97        33

    accuracy                           0.98       120
   macro avg       0.98      0.98      0.98       120
weighted avg       0.98      0.98      0.98       120

Confusion Matrix:
 [[86  1]
 [ 1 32]]


In [ ]:
rf_train_accuracy = rf.score(X_train_70, y_train_70)
rf_test_accuracy = rf.score(X_test_70, y_test_70)

print("Random Forest Training Accuracy (in %):", rf_train_accuracy*100)
print("\nRandom Forest Testing Accuracy (in %):", rf_test_accuracy*100)

Random Forest Training Accuracy (in %): 100.0

Random Forest Testing Accuracy (in %): 98.33333333333333


#**DECISION TREE CLASSIFIER MODEL :**

In [ ]:
# DECISION TREE CLASSIFIER:

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
# dt = DecisionTreeClassifier()

# Training the model on the 70:30 split:
dt.fit(X_train_70, y_train_70)

# Predictions on the test set:
y_pred_70_dt = dt.predict(X_test_70)

accuracy_70_dt = accuracy_score(y_test_70, y_pred_70_dt)

print("Decision Tree Accuracy on 70:30 split (in %):", accuracy_70_dt*100)

print("\nClassification Report:\n", classification_report(y_test_70, y_pred_70_dt))

print("Confusion Matrix:\n", confusion_matrix(y_test_70, y_pred_70_dt))

Decision Tree Accuracy on 70:30 split (in %): 98.33333333333333

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.98      0.99        87
           1       0.94      1.00      0.97        33

    accuracy                           0.98       120
   macro avg       0.97      0.99      0.98       120
weighted avg       0.98      0.98      0.98       120

Confusion Matrix:
 [[85  2]
 [ 0 33]]


In [ ]:
dt_train_accuracy = dt.score(X_train_70, y_train_70)
dt_test_accuracy = dt.score(X_test_70, y_test_70)

print("Decision Tree Training Accuracy (in %):", dt_train_accuracy*100)
print("\nDecision Tree Testing Accuracy (in %):", dt_test_accuracy*100)

Decision Tree Training Accuracy (in %): 100.0

Decision Tree Testing Accuracy (in %): 98.33333333333333


# **XGBOOST CLASSIFIER MODEL:**

In [ ]:
# XGBOOST CLASSIFIER:

from xgboost import XGBClassifier

# xgb = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss')
xgb = XGBClassifier()

# Training the model on the 70:30 split:
xgb.fit(X_train_70, y_train_70)

# Predictions on the test set:
y_pred_70_xgb = xgb.predict(X_test_70)

# Accuracy:
accuracy_70_xgb = accuracy_score(y_test_70, y_pred_70_xgb)

print("XGBoost Accuracy on 70:30 split (in %):", accuracy_70_xgb*100)

print("\nClassification Report:\n", classification_report(y_test_70, y_pred_70_xgb))

print("Confusion Matrix:\n", confusion_matrix(y_test_70, y_pred_70_xgb))

XGBoost Accuracy on 70:30 split (in %): 98.33333333333333

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.98      0.99        87
           1       0.94      1.00      0.97        33

    accuracy                           0.98       120
   macro avg       0.97      0.99      0.98       120
weighted avg       0.98      0.98      0.98       120

Confusion Matrix:
 [[85  2]
 [ 0 33]]


In [ ]:
xgb_train_accuracy = xgb.score(X_train_70, y_train_70)
xgb_test_accuracy = xgb.score(X_test_70, y_test_70)

print("XGBoost Training Accuracy (in %):", xgb_train_accuracy*100)
print("\nXGBoost Testing Accuracy (in %):", xgb_test_accuracy*100)

XGBoost Training Accuracy (in %): 100.0

XGBoost Testing Accuracy (in %): 98.33333333333333


# **ADABOOST CLASSIFIER MODEL:**

In [ ]:
# ADABOOST CLASSIFIER:

from sklearn.ensemble import AdaBoostClassifier

# ada = AdaBoostClassifier(random_state=42, n_estimators=50)
ada = AdaBoostClassifier()

# Training the model on the 70:30 split:
ada.fit(X_train_70, y_train_70)

# Predictions on the test set:
y_pred_70_ada = ada.predict(X_test_70)

# Accuracy:
accuracy_70_ada = accuracy_score(y_test_70, y_pred_70_ada)

print("AdaBoost Accuracy on 70:30 split (in %):", accuracy_70_ada*100)

print("\nClassification Report:\n", classification_report(y_test_70, y_pred_70_ada))

print("Confusion Matrix:\n", confusion_matrix(y_test_70, y_pred_70_ada))

AdaBoost Accuracy on 70:30 split (in %): 98.33333333333333

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99        87
           1       0.97      0.97      0.97        33

    accuracy                           0.98       120
   macro avg       0.98      0.98      0.98       120
weighted avg       0.98      0.98      0.98       120

Confusion Matrix:
 [[86  1]
 [ 1 32]]


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


In [ ]:
ada_train_accuracy = ada.score(X_train_70, y_train_70)
ada_test_accuracy = ada.score(X_test_70, y_test_70)

print("AdaBoost Training Accuracy (in %):", ada_train_accuracy*100)
print("\nAdaBoost Testing Accuracy (in %):", ada_test_accuracy*100)

AdaBoost Training Accuracy (in %): 100.0

AdaBoost Testing Accuracy (in %): 98.33333333333333


# **K NEAREST NEIGHBOURS CLASSIFIER MODEL :**

In [ ]:
# K NEAREST NEIGHBOURS CLASSIFIER:

from sklearn.neighbors import KNeighborsClassifier

# Initialize KNN classifier with a chosen value of k (e.g., 5):
knn = KNeighborsClassifier(n_neighbors=5)

# Training the KNN model on the 70:30 split:
knn.fit(X_train_70, y_train_70)

# Predictions on the test set:
y_pred_70_knn = knn.predict(X_test_70)

# Accuracy of the model:
knn_accuracy = accuracy_score(y_test_70, y_pred_70_knn)

print("KNN Accuracy on 70:30 split (in %):", knn_accuracy*100)

print("\nClassification Report:\n", classification_report(y_test_70, y_pred_70_knn))

print("Confusion Matrix:\n", confusion_matrix(y_test_70, y_pred_70_knn))

KNN Accuracy on 70:30 split (in %): 62.5

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.60      0.70        87
           1       0.40      0.70      0.51        33

    accuracy                           0.62       120
   macro avg       0.62      0.65      0.60       120
weighted avg       0.72      0.62      0.65       120

Confusion Matrix:
 [[52 35]
 [10 23]]


In [ ]:
knn_train_accuracy = knn.score(X_train_70, y_train_70)
knn_test_accuracy = knn.score(X_test_70, y_test_70)

print("KNN Training Accuracy (in %):", knn_train_accuracy*100)
print("\nKNN Testing Accuracy (in %):", knn_test_accuracy*100)

KNN Training Accuracy (in %): 72.66187050359713

KNN Testing Accuracy (in %): 62.5


# **NAIVE BAYES CLASSIFIER MODEL :**

In [ ]:
# NAIVE BAYES CLASSIFIER (After Scaling):

from sklearn.naive_bayes import GaussianNB

# Initialize Gaussian Naive Bayes classifier:
nb = GaussianNB()

# Training the Naive Bayes model on the scaled 70:30 split:
nb.fit(X_train_70_scaled, y_train_70)

# Predictions on the test set:
y_pred_70_nb = nb.predict(X_test_70_scaled)

# Accuracy:
nb_accuracy = accuracy_score(y_test_70, y_pred_70_nb)

print("Naive Bayes Accuracy on 70:30 split (in %):", nb_accuracy*100)

print("\nClassification Report:\n", classification_report(y_test_70, y_pred_70_nb))

print("Confusion Matrix:\n", confusion_matrix(y_test_70, y_pred_70_nb))

Naive Bayes Accuracy on 70:30 split (in %): 88.33333333333333

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.86      0.91        87
           1       0.72      0.94      0.82        33

    accuracy                           0.88       120
   macro avg       0.85      0.90      0.87       120
weighted avg       0.90      0.88      0.89       120

Confusion Matrix:
 [[75 12]
 [ 2 31]]


In [ ]:
nb_train_accuracy = nb.score(X_train_70_scaled, y_train_70)
nb_test_accuracy = nb.score(X_test_70_scaled, y_test_70)

print("Naive Bayes Training Accuracy (in %):", nb_train_accuracy*100)
print("\nNaive Bayes Testing Accuracy (in %):", nb_test_accuracy*100)

Naive Bayes Training Accuracy (in %): 89.92805755395683

Naive Bayes Testing Accuracy (in %): 88.33333333333333


In [ ]:
# NAIVE BAYES CLASSIFIER (Without Scaling):

from sklearn.naive_bayes import GaussianNB

# Initialize Gaussian Naive Bayes classifier:
nb = GaussianNB()

# Training the Naive Bayes model on the 70:30 split:
nb.fit(X_train_70, y_train_70)

# Predictions on the test set:
y_pred_70_nb = nb.predict(X_test_70)

# Accuracy:
nb_accuracy = accuracy_score(y_test_70, y_pred_70_nb)

print("Naive Bayes Accuracy on 70:30 split (in %):", nb_accuracy*100)

print("\nClassification Report:\n", classification_report(y_test_70, y_pred_70_nb))

print("Confusion Matrix:\n", confusion_matrix(y_test_70, y_pred_70_nb))

Naive Bayes Accuracy on 70:30 split (in %): 88.33333333333333

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.86      0.91        87
           1       0.72      0.94      0.82        33

    accuracy                           0.88       120
   macro avg       0.85      0.90      0.87       120
weighted avg       0.90      0.88      0.89       120

Confusion Matrix:
 [[75 12]
 [ 2 31]]


In [ ]:
nb_train_accuracy = nb.score(X_train_70, y_train_70)
nb_test_accuracy = nb.score(X_test_70, y_test_70)

print("Naive Bayes Training Accuracy (in %):", nb_train_accuracy*100)
print("\nNaive Bayes Testing Accuracy (in %):", nb_test_accuracy*100)

Naive Bayes Training Accuracy (in %): 89.92805755395683

Naive Bayes Testing Accuracy (in %): 88.33333333333333


#**MODEL ACCURACY COMPARISON :**

In [ ]:
import pandas as pd

data = {
    'Model': [
        'Logistic Regression',
        'Random Forest',
        'Decision Tree',
        'XGBoost',
        'AdaBoost',
        'K-Nearest Neighbors',
        'Naive Bayes'
    ],
    'Training Accuracy': [
        logreg_train_accuracy,
        rf_train_accuracy,
        dt_train_accuracy,
        xgb_train_accuracy,
        ada_train_accuracy,
        knn_train_accuracy,
        nb_train_accuracy
    ],
    'Testing Accuracy': [
        logreg_test_accuracy,
        rf_test_accuracy,
        dt_test_accuracy,
        xgb_test_accuracy,
        ada_test_accuracy,
        knn_test_accuracy,
        nb_test_accuracy
    ],
    'Overall Accuracy': [
        accuracy_70,
        accuracy_70_rf,
        accuracy_70_dt,
        accuracy_70_xgb,
        accuracy_70_ada,
        knn_accuracy,
        nb_accuracy
    ]
}

comparison_df = pd.DataFrame(data)

comparison_df['Training Accuracy'] = comparison_df['Training Accuracy'].apply(lambda x: f"{x*100:.2f}%")
comparison_df['Testing Accuracy'] = comparison_df['Testing Accuracy'].apply(lambda x: f"{x*100:.2f}%")
comparison_df['Overall Accuracy'] = comparison_df['Overall Accuracy'].apply(lambda x: f"{x*100:.2f}%")

from IPython.display import display
display(comparison_df)

Model Training Accuracy Testing Accuracy Overall Accuracy
0  Logistic Regression            58.63%           61.67%           61.67%
1        Random Forest           100.00%           98.33%           98.33%
2        Decision Tree           100.00%           98.33%           98.33%
3              XGBoost           100.00%           98.33%           98.33%
4             AdaBoost           100.00%           98.33%           98.33%
5  K-Nearest Neighbors            72.66%           62.50%           62.50%
6          Naive Bayes            89.93%           88.33%           88.33%

#**HYPERPARAMETER TUNING :**

In [ ]:
# HYPERPARAMETER TUNING NAIVE BAYES MODEL:

from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

nb = GaussianNB()

# Defining a parameter grid for Naive Bayes:
param_grid = {
    'var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6, 1e-5]
}

# Setting up the GridSearchCV for hyperparameter tuning:
grid_search_nb = GridSearchCV(estimator=nb, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1)

# Fitting the model to the training data:
grid_search_nb.fit(X_train_70, y_train_70)

# Best parameters and Best score:
best_nb_params = grid_search_nb.best_params_
best_nb_model = grid_search_nb.best_estimator_
best_nb_score = grid_search_nb.best_score_

# Display the best parameter
print("Best var_smoothing parameter:", best_nb_params['var_smoothing'])

# Predictions on the test set using the best model
y_pred_70_nb_tuned = best_nb_model.predict(X_test_70)

print("Best parameters found: ", best_nb_params)
print("Best cross-validation accuracy: {:.2f}%".format(best_nb_score * 100))

Best var_smoothing parameter: 1e-09
Best parameters found:  {'var_smoothing': 1e-09}
Best cross-validation accuracy: 89.58%


In [ ]:
# Accuracy, classification report, and confusion matrix:
nb_accuracy_tuned = accuracy_score(y_test_70, y_pred_70_nb_tuned)

print("\nNaive Bayes Accuracy on 70:30 split after tuning (in %):", nb_accuracy_tuned * 100)
print("\nClassification Report:\n", classification_report(y_test_70, y_pred_70_nb_tuned))
print("Confusion Matrix:\n", confusion_matrix(y_test_70, y_pred_70_nb_tuned))


Naive Bayes Accuracy on 70:30 split after tuning (in %): 88.33333333333333

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.86      0.91        87
           1       0.72      0.94      0.82        33

    accuracy                           0.88       120
   macro avg       0.85      0.90      0.87       120
weighted avg       0.90      0.88      0.89       120

Confusion Matrix:
 [[75 12]
 [ 2 31]]


In [ ]:
# HYPERPARAMETER TUNING NAIVE BAYES MODEL (COMPARISON):

# --- Initial Model (Before Tuning) ---

print("Before Tuning:")
print("Training Accuracy (initial): {:.2f} %".format(nb_train_accuracy * 100))
print("Testing Accuracy (initial): {:.2f} %".format(nb_test_accuracy * 100))

# --- Tuned Model (After Hyperparameter Tuning) ---

train_accuracy_tuned_nb = accuracy_score(y_train_70, best_nb_model.predict(X_train_70))
test_accuracy_tuned_nb = accuracy_score(y_test_70, best_nb_model.predict(X_test_70))

print("\nAfter Tuning:")
print("Training Accuracy (tuned): {:.2f}%".format(train_accuracy_tuned_nb * 100))
print("Testing Accuracy (tuned): {:.2f}%".format(test_accuracy_tuned_nb * 100))

Before Tuning:
Training Accuracy (initial): 89.93 %
Testing Accuracy (initial): 88.33 %

After Tuning:
Training Accuracy (tuned): 89.93%
Testing Accuracy (tuned): 88.33%


In [ ]:
# HYPERPARAMETER TUNING LOGISTIC REGRESSION:

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# logreg = LogisticRegression(max_iter=1000, random_state=42)
# Scale the features (this helps in convergence for Logistic Regression)
# scaler = StandardScaler()
# X_train_70_scaled = scaler.fit_transform(X_train_70)
# X_test_70_scaled = scaler.transform(X_test_70)

# Defining parameter grid for Logistic Regression:
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],  # Regularization strength
    'solver': ['liblinear', 'lbfgs', 'newton-cg', 'saga'],  # Different solvers
    'max_iter': [100, 500, 1000]  # Iterations for convergence
}

# Setting up GridSearchCV:
grid_search_logreg = GridSearchCV(estimator=LogisticRegression(random_state=42),
                                  param_grid=param_grid,
                                  cv=5,
                                  scoring='accuracy',
                                  n_jobs=-1)

# Fitting the model on the training data:
grid_search_logreg.fit(X_train_70_scaled, y_train_70)

# Getting the best parameters and estimator from GridSearchCV:
best_logreg_model = grid_search_logreg.best_estimator_
best_logreg_params = grid_search_logreg.best_params_
best_logreg_score = grid_search_logreg.best_score_

# Predictions on the test set using the tuned model:
y_pred_tuned_logreg = best_logreg_model.predict(X_test_70_scaled)

# Best parameters:
print("Best parameters found: ", best_logreg_params)
print("Best cross-validation accuracy: {:.2f}%".format(best_logreg_score * 100))

Best parameters found:  {'C': 0.001, 'max_iter': 100, 'solver': 'lbfgs'}
Best cross-validation accuracy: 60.43%


In [ ]:
# Accuracy, Classification report and Confusion matrix:

logreg_accuracy_tuned = accuracy_score(y_test_70, y_pred_tuned_logreg)

print("Best Parameters:", best_logreg_params)
print("\nLogistic Regression Accuracy on 70:30 split after Tuning (in %): {:.2f}%".format(logreg_accuracy_tuned * 100))
print("\nClassification Report (70:30 split):\n", classification_report(y_test_70, y_pred_tuned_logreg))
print("Confusion Matrix (70:30 split):\n", confusion_matrix(y_test_70, y_pred_tuned_logreg))

Best Parameters: {'C': 0.001, 'max_iter': 100, 'solver': 'lbfgs'}

Logistic Regression Accuracy on 70:30 split after Tuning (in %): 72.50%

Classification Report (70:30 split):
               precision    recall  f1-score   support

           0       0.72      1.00      0.84        87
           1       0.00      0.00      0.00        33

    accuracy                           0.72       120
   macro avg       0.36      0.50      0.42       120
weighted avg       0.53      0.72      0.61       120

Confusion Matrix (70:30 split):
 [[87  0]
 [33  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
# HYPERPARAMETER TUNING LOGISTIC REGRESSION (COMPARISON):

# --- Initial Model (Before Tuning) ---

print("Before Tuning:")
print("Training Accuracy (initial): {:.2f}%".format(logreg_train_accuracy * 100))
print("Testing Accuracy (initial): {:.2f}%".format(logreg_test_accuracy * 100))

# --- Tuned Model (After Hyperparameter Tuning) ---

train_accuracy_tuned_logreg = accuracy_score(y_train_70, best_logreg_model.predict(X_train_70_scaled))
test_accuracy_tuned_logreg = accuracy_score(y_test_70, best_logreg_model.predict(X_test_70_scaled))

print("\nAfter Tuning:")
print("Training Accuracy (tuned): {:.2f}%".format(train_accuracy_tuned_logreg * 100))
print("Testing Accuracy (tuned): {:.2f}%".format(test_accuracy_tuned_logreg * 100))

Before Tuning:
Training Accuracy (initial): 58.63%
Testing Accuracy (initial): 61.67%

After Tuning:
Training Accuracy (tuned): 60.43%
Testing Accuracy (tuned): 72.50%


In [ ]:
# HYPERPARAMETER TUNING RANDOM FOREST CLASSIFIER MODEL:

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Defining parameter grid for Random Forest:
param_grid_rf = {
    'n_estimators': [50, 100, 200],               # Number of trees in the forest
    'max_depth': [None, 10, 20, 30],              # Maximum depth of the tree
    'min_samples_split': [2, 5, 10],              # Minimum samples required to split an internal node
    'min_samples_leaf': [1, 2, 4],                # Minimum samples required to be at a leaf node
    'max_features': ['auto', 'sqrt', 'log2'],     # Number of features to consider for the best split
    'bootstrap': [True, False]                    # Whether bootstrap samples are used when building trees
}

# Setting up GridSearchCV with 5-fold cross-validation:
grid_search_rf = GridSearchCV(estimator=RandomForestClassifier(random_state=42),
                              param_grid=param_grid_rf,
                              cv=5,
                              scoring='accuracy',
                              n_jobs=-1)

# Fitting the model to the training data:
grid_search_rf.fit(X_train_70, y_train_70)

# Best estimator and parameters from GridSearchCV
best_rf_model = grid_search_rf.best_estimator_
best_rf_params = grid_search_rf.best_params_
best_rf_score = grid_search_rf.best_score_

# Best parameters and cross-validation score:
print("Best parameters found: ", best_rf_params)
print("Best cross-validation accuracy: {:.2f}%".format(best_rf_score * 100))

# Predictions on the test set using the tuned model:
y_pred_tuned_rf = best_rf_model.predict(X_test_70)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:540: FitFailedWarning: 
1080 fits failed out of a total of 3240.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
611 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/ut

Best parameters found:  {'bootstrap': False, 'max_depth': None, 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 50}
Best cross-validation accuracy: 96.76%


In [ ]:
# Accuracy, Classification Report, and Confusion Matrix:

rf_accuracy_tuned = accuracy_score(y_test_70, y_pred_tuned_rf)

print("\nRandom Forest Accuracy on Test Set after tuning (in %): {:.2f} %".format(rf_accuracy_tuned * 100))
print("\nClassification Report (Tuned Random Forest):\n", classification_report(y_test_70, y_pred_tuned_rf))
print("Confusion Matrix (Tuned Random Forest):\n", confusion_matrix(y_test_70, y_pred_tuned_rf))


Random Forest Accuracy on Test Set after tuning (in %): 98.33 %

Classification Report (Tuned Random Forest):
               precision    recall  f1-score   support

           0       1.00      0.98      0.99        87
           1       0.94      1.00      0.97        33

    accuracy                           0.98       120
   macro avg       0.97      0.99      0.98       120
weighted avg       0.98      0.98      0.98       120

Confusion Matrix (Tuned Random Forest):
 [[85  2]
 [ 0 33]]


In [ ]:
# HYPERPARAMETER TUNING RANDOM FOREST (COMPARISON):

# --- Initial Model (Before Tuning) ---

print("Before Tuning:")
print("Training Accuracy (initial): {:.2f}%".format(rf_train_accuracy * 100))
print("Testing Accuracy (initial): {:.2f}%".format(rf_test_accuracy * 100))

# --- Tuned Model (After Hyperparameter Tuning) ---

train_accuracy_tuned_rf = accuracy_score(y_train_70, best_rf_model.predict(X_train_70))
test_accuracy_tuned_rf = accuracy_score(y_test_70, best_rf_model.predict(X_test_70))

print("\nAfter Tuning:")
print("Training Accuracy (tuned): {:.2f}%".format(train_accuracy_tuned_rf * 100))
print("Testing Accuracy (tuned): {:.2f}%".format(test_accuracy_tuned_rf * 100))

Before Tuning:
Training Accuracy (initial): 100.00%
Testing Accuracy (initial): 98.33%

After Tuning:
Training Accuracy (tuned): 100.00%
Testing Accuracy (tuned): 98.33%


In [ ]:
# HYPERPARAMETER TUNING DECISION TREE CLASSIFIER MODEL:

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Defining the parameter grid for Decision Tree:
param_grid_dt = {
    'criterion': ['gini', 'entropy'],                 # Criterion for splitting
    'max_depth': [None, 10, 20, 30, 50],              # Maximum depth of the tree
    'min_samples_split': [2, 10, 20, 30],             # Minimum samples required to split
    'min_samples_leaf': [1, 5, 10],                   # Minimum samples required at leaf node
    'max_features': [None, 'sqrt', 'log2']            # Number of features to consider for best split
}

grid_search_dt = GridSearchCV(estimator=DecisionTreeClassifier(random_state=42),
                              param_grid=param_grid_dt,
                              cv=5,
                              scoring='accuracy',
                              n_jobs=-1)

# Fitting the model on the training data:
grid_search_dt.fit(X_train_70, y_train_70)

# Best model after hyperparameter tuning:
best_dt_model = grid_search_dt.best_estimator_
best_dt_params = grid_search_dt.best_params_
best_dt_score = grid_search_dt.best_score_

# Predictions on the test set using the tuned model:
y_pred_tuned_dt = best_dt_model.predict(X_test_70)

# Best parameters & cross-validation accuracy:
print("Best parameters found: ", best_dt_params)
print("Best cross-validation accuracy: {:.2f} %".format(best_dt_score * 100))

Best parameters found:  {'criterion': 'entropy', 'max_depth': None, 'max_features': None, 'min_samples_leaf': 10, 'min_samples_split': 2}
Best cross-validation accuracy: 97.11 %


In [ ]:
# Accuracy, Classification Report, and Confusion Matrix:

dt_accuracy_tuned = accuracy_score(y_test_70, y_pred_tuned_dt)

print("\nDecision Tree accuracy on Test Set after tuning (in %): {:.2f} %".format(dt_accuracy_tuned * 100))
print("\nClassification Report for Tuned Model:\n", classification_report(y_test_70, y_pred_tuned_dt))
print("Confusion Matrix for Tuned Model:\n", confusion_matrix(y_test_70, y_pred_tuned_dt))


Decision Tree accuracy on Test Set after tuning (in %): 98.33 %

Classification Report for Tuned Model:
               precision    recall  f1-score   support

           0       1.00      0.98      0.99        87
           1       0.94      1.00      0.97        33

    accuracy                           0.98       120
   macro avg       0.97      0.99      0.98       120
weighted avg       0.98      0.98      0.98       120

Confusion Matrix for Tuned Model:
 [[85  2]
 [ 0 33]]


In [ ]:
# HYPERPARAMETER TUNING DECISION TREE (COMPARISON):

# --- Initial Model (Before Tuning) ---

print("Before Tuning:")
print("Training Accuracy (initial): {:.2f}%".format(dt_train_accuracy * 100))
print("Testing Accuracy (initial): {:.2f}%".format(dt_test_accuracy * 100))

# --- Tuned Model (After Hyperparameter Tuning) ---

train_accuracy_tuned_dt = accuracy_score(y_train_70, best_dt_model.predict(X_train_70))
test_accuracy_tuned_dt = accuracy_score(y_test_70, best_dt_model.predict(X_test_70))

print("\nAfter Tuning:")
print("Training Accuracy (tuned): {:.2f}%".format(train_accuracy_tuned_dt * 100))
print("Testing Accuracy (tuned): {:.2f}%".format(test_accuracy_tuned_dt * 100))

Before Tuning:
Training Accuracy (initial): 100.00%
Testing Accuracy (initial): 98.33%

After Tuning:
Training Accuracy (tuned): 98.20%
Testing Accuracy (tuned): 98.33%


In [ ]:
# HYPERPARAMETER TUNING KNN MODEL:

from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Defining parameter grid for KNN:
param_grid_knn = {
    'n_neighbors': [3, 5, 7, 9, 11],             # Number of neighbors
    'weights': ['uniform', 'distance'],           # Weight function
    'metric': ['euclidean', 'manhattan', 'minkowski']  # Distance metric
}

# Setting up GridSearchCV with 5-fold cross-validation:
grid_search_knn = GridSearchCV(estimator=KNeighborsClassifier(),
                               param_grid=param_grid_knn,
                               cv=5,
                               scoring='accuracy',
                               n_jobs=-1)

# Fitting the model on the training data:
grid_search_knn.fit(X_train_70, y_train_70)

# Getting the best parameters and estimator from GridSearchCV:
best_knn_model = grid_search_knn.best_estimator_
best_knn_params = grid_search_knn.best_params_
best_knn_score = grid_search_knn.best_score_

# Predictions on the test set using the tuned model:
y_pred_tuned_knn = best_knn_model.predict(X_test_70)

print("Best parameters found: ", best_knn_params)
print("Best cross-validation accuracy: {:.2f}%".format(best_knn_score * 100))

Best parameters found:  {'metric': 'manhattan', 'n_neighbors': 9, 'weights': 'distance'}
Best cross-validation accuracy: 66.89%


In [ ]:
# Accuracy, Classification Report, and Confusion Matrix:

knn_accuracy_tuned = accuracy_score(y_test_70, y_pred_tuned_knn)

print("\nKNN accuracy on Test Set after tuning (in %): {:.2f} %".format(knn_accuracy_tuned * 100))
print("\nClassification Report for Tuned Model:\n", classification_report(y_test_70, y_pred_tuned_knn))
print("Confusion Matrix for Tuned Model:\n", confusion_matrix(y_test_70, y_pred_tuned_knn))


KNN accuracy on Test Set after tuning (in %): 62.50 %

Classification Report for Tuned Model:
               precision    recall  f1-score   support

           0       0.85      0.59      0.69        87
           1       0.40      0.73      0.52        33

    accuracy                           0.62       120
   macro avg       0.62      0.66      0.61       120
weighted avg       0.73      0.62      0.64       120

Confusion Matrix for Tuned Model:
 [[51 36]
 [ 9 24]]


In [ ]:
# HYPERPARAMETER TUNING KNN MODEL (COMPARISON):

# --- Initial Model (Before Tuning) ---

print("Before Tuning:")
print("Training Accuracy (initial): {:.2f}%".format(knn_train_accuracy * 100))
print("Testing Accuracy (initial): {:.2f}%".format(knn_test_accuracy * 100))

# --- Tuned Model (After Hyperparameter Tuning) ---

train_accuracy_tuned_knn = accuracy_score(y_train_70, best_knn_model.predict(X_train_70))
test_accuracy_tuned_knn = accuracy_score(y_test_70, best_knn_model.predict(X_test_70))

print("\nAfter Tuning:")
print("Training Accuracy (tuned): {:.2f}%".format(train_accuracy_tuned_knn * 100))
print("Testing Accuracy (tuned): {:.2f}%".format(test_accuracy_tuned_knn * 100))

Before Tuning:
Training Accuracy (initial): 72.66%
Testing Accuracy (initial): 62.50%

After Tuning:
Training Accuracy (tuned): 100.00%
Testing Accuracy (tuned): 62.50%


In [ ]:
# HYPERPARAMETER TUNING XGBOOST MODEL:

from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Define parameter grid for XGBoost:
param_grid_xgb = {
    'n_estimators': [50, 100, 200],              # Number of boosting rounds
    'learning_rate': [0.01, 0.1, 0.2, 0.3],      # Step size shrinkage
    'max_depth': [3, 5, 7],                      # Maximum tree depth
    'subsample': [0.6, 0.8, 1.0],                # Fraction of samples to use per tree
    'colsample_bytree': [0.6, 0.8, 1.0],         # Fraction of features to consider per split
    'gamma': [0, 0.1, 0.2]                       # Minimum loss reduction required to make a split
}

# Set up GridSearchCV with 5-fold cross-validation:
grid_search_xgb = GridSearchCV(estimator=XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss'),
                               param_grid=param_grid_xgb,
                               cv=5,
                               scoring='accuracy',
                               n_jobs=-1)

# Fitting the model on the training data:
grid_search_xgb.fit(X_train_70, y_train_70)

# Retrieve the best model, parameters, and cross-validation score:
best_xgb_model = grid_search_xgb.best_estimator_
best_xgb_params = grid_search_xgb.best_params_
best_xgb_score = grid_search_xgb.best_score_

# Predictions on the test set with the tuned model:
y_pred_tuned_xgb = best_xgb_model.predict(X_test_70)

# Best Parameters:
print("Best parameters found: ", best_xgb_params)
print("Best cross-validation accuracy: {:.2f}%".format(best_xgb_score * 100))

Best parameters found:  {'colsample_bytree': 0.8, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200, 'subsample': 1.0}
Best cross-validation accuracy: 97.84%


/usr/local/lib/python3.10/dist-packages/xgboost/core.py:158: UserWarning: [13:24:22] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


In [ ]:
# Accuracy, Classification Report and Confusion Matrix after tuning:

xgb_accuracy_tuned = accuracy_score(y_test_70, y_pred_tuned_xgb)

print("\nXGBoost Test Accuracy: {:.2f}%".format(accuracy_score(y_test_70, y_pred_tuned_xgb) * 100))
print("\nClassification Report:\n", classification_report(y_test_70, y_pred_tuned_xgb))
print("Confusion Matrix:\n", confusion_matrix(y_test_70, y_pred_tuned_xgb))


XGBoost Test Accuracy: 97.50%

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.98      0.98        87
           1       0.94      0.97      0.96        33

    accuracy                           0.97       120
   macro avg       0.96      0.97      0.97       120
weighted avg       0.98      0.97      0.98       120

Confusion Matrix:
 [[85  2]
 [ 1 32]]


In [ ]:
# HYPERPARAMETER TUNING XGBOOST MODEL (COMPARISON):

# --- Initial Model (Before Tuning) ---

print("Before Tuning:")
print("Training Accuracy (initial): {:.2f}%".format(xgb_train_accuracy * 100))
print("Testing Accuracy (initial): {:.2f}%".format(xgb_test_accuracy * 100))

# --- Tuned Model (After Hyperparameter Tuning) ---

train_accuracy_tuned_xgb = accuracy_score(y_train_70, best_xgb_model.predict(X_train_70))
test_accuracy_tuned_xgb = accuracy_score(y_test_70, best_xgb_model.predict(X_test_70))

print("\nAfter Tuning:")
print("Training Accuracy (tuned): {:.2f}%".format(train_accuracy_tuned_xgb * 100))
print("Testing Accuracy (tuned): {:.2f}%".format(test_accuracy_tuned_xgb * 100))

Before Tuning:
Training Accuracy (initial): 100.00%
Testing Accuracy (initial): 98.33%

After Tuning:
Training Accuracy (tuned): 100.00%
Testing Accuracy (tuned): 97.50%


# **HYPERPARAMETER TUNING ACCURACY COMPARISON :**

In [ ]:
from IPython.display import display, HTML
import pandas as pd

# Data for the table with actual variable names
data = {
    "Model": ["Logistic Regression", "K-Nearest Neighbors", "Decision Tree", "Random Forest", "XGBoost", "Naive Bayes"],
    "Training Accuracy (Before Tuning)": [
        logreg_train_accuracy * 100,
        knn_train_accuracy * 100,
        dt_train_accuracy * 100,
        rf_train_accuracy * 100,
        xgb_train_accuracy * 100,
        nb_train_accuracy * 100
    ],
    "Testing Accuracy (Before Tuning)": [
        logreg_test_accuracy * 100,
        knn_test_accuracy * 100,
        dt_test_accuracy * 100,
        rf_test_accuracy * 100,
        xgb_test_accuracy * 100,
        nb_test_accuracy * 100
    ],
    "Training Accuracy (After Tuning)": [
        train_accuracy_tuned_logreg * 100,
        train_accuracy_tuned_knn * 100,
        train_accuracy_tuned_dt * 100,
        train_accuracy_tuned_rf * 100,
        train_accuracy_tuned_xgb * 100,
        train_accuracy_tuned_nb * 100
    ],
    "Testing Accuracy (After Tuning)": [
        test_accuracy_tuned_logreg * 100,
        test_accuracy_tuned_knn * 100,
        test_accuracy_tuned_dt * 100,
        test_accuracy_tuned_rf * 100,
        test_accuracy_tuned_xgb * 100,
        test_accuracy_tuned_nb * 100
    ]
}

# Creating DataFrame
vis = pd.DataFrame(data)

# Displaying the table with formatted percentages
display(HTML(vis.to_html(index=False, float_format="%.2f %%")))

# **RETRAINING SELECTED MODELS WITH BEST PARAMETERS :**

In [ ]:
# RETRAINING XGBOOST MODEL USING BEST PARAMETERS:

from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Defining the XGBoost model with the best parameters:
final_xgb_model = XGBClassifier(
    colsample_bytree=0.8,
    gamma=0,
    learning_rate=0.1,
    max_depth=3,
    n_estimators=200,
    subsample=1.0,
)

# Training the final model on the entire training dataset:
final_xgb_model.fit(X_train_70, y_train_70)

# Predictions on the test set:
y_pred_final_xgb = final_xgb_model.predict(X_test_70)

# Evaluating the model:
final_accuracy = accuracy_score(y_test_70, y_pred_final_xgb)
print("Final XGBoost Model Accuracy (in %): {:.2f}%".format(final_accuracy * 100))

# Classification report and confusion matrix:
print("\nClassification Report:\n", classification_report(y_test_70, y_pred_final_xgb))
print("Confusion Matrix:\n", confusion_matrix(y_test_70, y_pred_final_xgb))

Final XGBoost Model Accuracy (in %): 97.50%

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.98      0.98        87
           1       0.94      0.97      0.96        33

    accuracy                           0.97       120
   macro avg       0.96      0.97      0.97       120
weighted avg       0.98      0.97      0.98       120

Confusion Matrix:
 [[85  2]
 [ 1 32]]


In [ ]:
# FINAL TRAINING & TESTING ACCURACY XGBOOST:

train_accuracy_final_xgb = accuracy_score(y_train_70, final_xgb_model.predict(X_train_70))

test_accuracy_final_xgb = accuracy_score(y_test_70, y_pred_final_xgb)

print("Final Training Accuracy (in %): {:.2f}%".format(train_accuracy_final_xgb * 100))
print("Final Testing Accuracy (in %): {:.2f}%".format(test_accuracy_final_xgb * 100))

Final Training Accuracy (in %): 100.00%
Final Testing Accuracy (in %): 97.50%


In [ ]:
# Saving the trained XGBoost model:

import joblib

joblib.dump(final_xgb_model, 'final_xgboost_model.pkl')

print("Model saved successfully as 'final_xgboost_model.pkl'")

Model saved successfully as 'final_xgboost_model.pkl'


In [ ]:
# RETRAINING DECISION TREE MODEL USING BEST PARAMETERS:

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Defining the Decision Tree model with the best parameters:
final_dt_model = DecisionTreeClassifier(
    criterion='entropy',
    max_depth=None,
    max_features=None,
    min_samples_leaf=10,
    min_samples_split=2,
)

# Training the final model on the entire training dataset:
final_dt_model.fit(X_train_70, y_train_70)

# Predictions on the test set:
y_pred_final_dt = final_dt_model.predict(X_test_70)

# Evaluating the model:
final_accuracy_dt = accuracy_score(y_test_70, y_pred_final_dt)
print("Final Decision Tree Model Accuracy (in %): {:.2f}%".format(final_accuracy_dt * 100))

# Classification report and confusion matrix:
print("\nClassification Report:\n", classification_report(y_test_70, y_pred_final_dt))
print("Confusion Matrix:\n", confusion_matrix(y_test_70, y_pred_final_dt))

Final Decision Tree Model Accuracy (in %): 98.33%

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.98      0.99        87
           1       0.94      1.00      0.97        33

    accuracy                           0.98       120
   macro avg       0.97      0.99      0.98       120
weighted avg       0.98      0.98      0.98       120

Confusion Matrix:
 [[85  2]
 [ 0 33]]


In [ ]:
# FINAL TRAINING & TESTING ACCURACY DECISION TREE:

train_accuracy_final_dt = accuracy_score(y_train_70, final_dt_model.predict(X_train_70))

test_accuracy_final_dt = accuracy_score(y_test_70, y_pred_final_dt)

print("Final Training Accuracy (in %): {:.2f}%".format(train_accuracy_final_dt * 100))
print("Final Testing Accuracy (in %): {:.2f}%".format(test_accuracy_final_dt * 100))

Final Training Accuracy (in %): 98.20%
Final Testing Accuracy (in %): 98.33%


In [ ]:
# Saving the trained Decision Tree model:

import joblib

joblib.dump(final_dt_model, 'final_dt_model.pkl')

print("Model saved successfully as 'final_dt_model.pkl'")

Model saved successfully as 'final_dt_model.pkl'


In [ ]:
# RETRAINING RANDOM FOREST MODEL USING BEST PARAMETERS:

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Defining the Random Forest model with the best parameters:
final_rf_model = RandomForestClassifier(
    bootstrap=False,
    max_depth=None,
    max_features='log2',
    min_samples_leaf=1,
    min_samples_split=5,
    n_estimators=50,
)

# Training the final model on the entire training dataset:
final_rf_model.fit(X_train_70, y_train_70)

# Predictions on the test set:
y_pred_final_rf = final_rf_model.predict(X_test_70)

# Evaluating the model:
final_accuracy_rf = accuracy_score(y_test_70, y_pred_final_rf)
print("Final Random Forest Model Accuracy (in %): {:.2f}%".format(final_accuracy_rf * 100))

# Classification report and confusion matrix:
print("\nClassification Report:\n", classification_report(y_test_70, y_pred_final_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test_70, y_pred_final_rf))

Final Random Forest Model Accuracy (in %): 97.50%

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.98      0.98        87
           1       0.94      0.97      0.96        33

    accuracy                           0.97       120
   macro avg       0.96      0.97      0.97       120
weighted avg       0.98      0.97      0.98       120

Confusion Matrix:
 [[85  2]
 [ 1 32]]


In [ ]:
# FINAL TRAINING & TESTING ACCURACY RANDOM FOREST:

train_accuracy_final_rf = accuracy_score(y_train_70, final_rf_model.predict(X_train_70))

test_accuracy_final_rf = accuracy_score(y_test_70, y_pred_final_rf)

print("Final Training Accuracy (in %): {:.2f}%".format(train_accuracy_final_rf * 100))
print("Final Testing Accuracy (in %): {:.2f}%".format(test_accuracy_final_rf * 100))

Final Training Accuracy (in %): 100.00%
Final Testing Accuracy (in %): 97.50%


In [ ]:
# Saving the trained Random Forest model:

import joblib

joblib.dump(final_rf_model, 'final_rf_model.pkl')

print("Model saved successfully as 'final_rf_model.pkl'")

Model saved successfully as 'final_rf_model.pkl'
